
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        batch_fetch_style: dynamic
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100


server:
  servlet:
    session:
      timeout:
  error:
    whitelabel:
      enabled: false

logging:
  level:
#    p6spy: info
    org.hibernate.SQL: trace
#    org.hibernate.type: trac


decorator:
  datasource:
    p6spy:
      enable-logging: true
#      multiline: true
#      logging: slf4j
#      tracing: